name: Build pull request

on:
  pull_request:
    paths:
      - ".github/workflows/pr-build.yml"
      - "app/**"
      - "gradle/**"
      - "build.graddle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials:
          # https://github.com/cycjimmy/semantic-release-action#private-packages
          persist-credentials: false
          fetch-depth: 0

      - name: Generate keystore
        run: keytool -genkey -v -keystore debugkey.jks -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "O=ReVanced"

      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew assembleRelease --no-daemon -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/debugkey.jks -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=androiddebugkey -Pandroid.injected.signing.key.password=android

      - name: Add hash to APK
        run: mv app/build/outputs/apk/release/app-release.apk revanced-manager-${{ github.sha }}.apk

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: revanced-manager
          path: revanced-manager-${{ github.sha }}.apk